// <auto-generated />
using API.Sale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.Sale.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623000000_AddUnaccentExtension")]
    partial class AddUnaccentExtension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasPostgresExtension("unaccent");
#pragma warning restore 612, 618
        }
    }
}
